version: "3.9"
services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres-db
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpwd"
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  pgadmin:
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "pguser@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    depends_on:
      - postgres

networks:
  default:
    driver: bridge