DBSettings:
  dbUser: "pguser"
  dbPassword: "pgpwd"
  dbHost: "localhost"
  dbPort: 5432
  dbName: "testdb"
  sslmode: "disable"

ProgramSettings:
  jiraUrl: "https://issues.apache.org/jira"
  threadCount: 5
  issueInOneRequest: 75
  maxTimeSleep: 300ms
  minTimeSleep: 10ms
  bindAddress: "127.0.0.1"

Server:
  port: "8080"
  readTimeout: 5m
  writeTimeout: 5m

log:
  level: info
  file: logs/logs.log
  error_file: logs/err_logs.log